[package]
name = "ppcasm"
version = "0.1.0"
edition = "2021"

[dependencies]
compact_str = "0.8"
object = { version = "0.36", features = ["write_std", "elf"], default-features = false }
smallvec = { version = "1", features = ["const_generics", "const_new", "union"] }
pratt = "0.4.0"
ariadne = "0.1.5"
unicode-ident = "1"
powerpc-asm = "0.4.1"
